import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { PageShell } from "@/components/NavRail";
import { AuthGate } from "@/components/chat/AuthGate";
import { Button } from "@/components/ui/button";
import { Markdown } from "@/components/chat/Markdown";
import { generateBriefing, getTodayBriefing, listBriefings } from "@/lib/briefing.functions";
import { Sparkles, RefreshCw, Calendar } from "lucide-react";

export const Route = createFileRoute("/briefing")({
  head: () => ({ meta: [{ title: "Daily Briefing — void" }] }),
  component: () => (<AuthGate><BriefingPage /></AuthGate>),
});

function BriefingPage() {
  const getToday = useServerFn(getTodayBriefing);
  const listFn = useServerFn(listBriefings);
  const genFn = useServerFn(generateBriefing);
  const qc = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const today = useQuery({ queryKey: ["briefing", "today"], queryFn: () => getToday() });
  const history = useQuery({ queryKey: ["briefing", "list"], queryFn: () => listFn() });

  const gen = useMutation({
    mutationFn: (force: boolean) => genFn({ data: { force } }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["briefing"] });
    },
  });

  const selected = selectedId
    ? history.data?.briefings.find((b) => b.id === selectedId)
    : null;

  const current = today.data?.briefing;

  return (
    <PageShell title="Daily Briefing" subtitle="Your morning readout — generated by void from your memory, conversations, and connections.">
      <div className="grid md:grid-cols-[1fr,280px] gap-6">
        <div className="min-w-0">
          {!current && !gen.isPending && (
            <div className="rounded-2xl border border-border/60 bg-card/40 p-8 text-center">
              <Sparkles className="mx-auto size-8 text-muted-foreground mb-3" />
              <p className="text-muted-foreground mb-4">No briefing yet for today.</p>
              <Button onClick={() => gen.mutate(false)}>Generate today's briefing</Button>
            </div>
          )}

          {gen.isPending && (
            <div className="rounded-2xl border border-border/60 bg-card/40 p-8 text-center text-muted-foreground">
              <RefreshCw className="mx-auto size-5 animate-spin mb-2" />
              Generating your briefing…
            </div>
          )}

          {current && (
            <article className="rounded-2xl border border-border/60 bg-card/40 p-6">
              <div className="flex items-center justify-between mb-4">
                <div className="text-xs uppercase tracking-wider text-muted-foreground">{current.for_date}</div>
                <Button variant="ghost" size="sm" onClick={() => gen.mutate(true)} disabled={gen.isPending}>
                  <RefreshCw className={`size-3.5 mr-1.5 ${gen.isPending ? "animate-spin" : ""}`} /> Regenerate
                </Button>
              </div>
              <div className="prose prose-invert prose-sm max-w-none">
                <Markdown content={current.content} />
              </div>
            </article>
          )}

          {selected && (
            <article className="mt-6 rounded-2xl border border-border/60 bg-card/40 p-6">
              <div className="text-xs uppercase tracking-wider text-muted-foreground mb-3">{selected.for_date}</div>
              <p className="text-sm text-muted-foreground">{selected.summary ?? "(no summary)"}</p>
            </article>
          )}
        </div>

        <aside>
          <div className="text-xs uppercase tracking-wider text-muted-foreground mb-2 flex items-center gap-1.5">
            <Calendar className="size-3.5" /> History
          </div>
          <ul className="space-y-1">
            {(history.data?.briefings ?? []).map((b) => (
              <li key={b.id}>
                <button
                  onClick={() => setSelectedId(b.id === selectedId ? null : b.id)}
                  className={`w-full text-left px-3 py-2 rounded-lg text-sm border ${b.id === selectedId ? "bg-white/5 border-white/20" : "border-transparent hover:bg-white/5"}`}
                >
                  <div className="font-medium">{b.for_date}</div>
                  {b.summary && <div className="text-xs text-muted-foreground line-clamp-2">{b.summary}</div>}
                </button>
              </li>
            ))}
            {history.data && history.data.briefings.length === 0 && (
              <li className="text-sm text-muted-foreground px-3 py-2">No past briefings yet.</li>
            )}
          </ul>
        </aside>
      </div>
    </PageShell>
  );
}
